### ISSUE TITLE
Setting up the doxygen.conf file?

### ISSUE THREAD

**Issue by mikelemo** [pieterdavid/mkdocs-doxygen-plugin#3]
How do you set this file? does it have to output latex? xml? can it accept warnings or other stuff? also where do things have to be in relation to each other in term of directory?

**Comment by pieterdavid** [comment]
Doxygen should be set up to generate html (other formats can be there, but will be ignored. Only the doxygen status code is checked - it is called from [here](https://github.com/pieterdavid/mkdocs-doxygen-plugin/blob/49b841b649acf58b668c0b805ab27f9e454920f4/mkdocsdoxygen/plugin.py#L50)). If the plugin is configured correctly to find the doxygen configuration file (see the last example [here](https://github.com/pieterdavid/mkdocs-doxygen-plugin#readme) for a case where it is not in the project root) it should be able to find out where to get the HTML output from ([this line](https://github.com/pieterdavid/mkdocs-doxygen-plugin/blob/49b841b649acf58b668c0b805ab27f9e454920f4/mkdocsdoxygen/plugin.py#L47) should be able to either read it from the configuration file, or put in the defaults).

**Comment by mikelemo** [comment]
So where exactly do you install the plugin?  does it have to be renamed afterwards? how to intigrate the doxygen outputs in markdown if you can't do that in rst?

I've got this plugins section on my mkdocs.yml:

```yml
plugins:
    - search
    - mermaid2
    - table-reader
    - doxygen:
      tryclone: no
      recursive: yes
      packages:
        - doxygen:
            url    : doxygen
        - doxyfwk:
            url    : https://github.com/cp3-llbb/Framework.git
            config : docs/doxygen.cfg
            workdir: . ## could be left out in this case

```
 
Does it suppose to have problems?

my doxygenfile is at "mkdocs/docs/doxygen.cfg" and mkdocs.yml @ "mkdocs/mkdocs.yml" 
Doxygen OUTPUT_DIRECTORY is set to ..\site\doxygen and HEML_GENERATION  is set to YES 

still getting errors like 👍 

> ERROR   -  Config value: 'plugins'. Error: Invalid Plugins configuration

Aborted with 1 Configuration Errors!

**Comment by pieterdavid** [comment]
`pip install git+https://github.com/pieterdavid/mkdocs-doxygen-plugin.git#egg=mkdocs-doxygen-plugin` (or the equivalent for how you manage python packages in the environment where mkdocs runs) should be sufficient.
Based on your description I would start with this configuration:
```yaml
plugins:
  - search
  - mermaid2
  - table-reader
  - doxygen:
      packages:
        - doxygen:
            url: .
            config: docs/doxygen.cfg
```
The Doxygen HTML output will just be put in a subdirectory of the mkdocs site (with the name of the package, so in the example above you can change the 'doxygen' under 'packages' to customise that), no other integration is done (the case for which I wrote the plugin just uses the HTML as part of the mkdocs site, the relevant mkdocs.yml fragments for that are [this](https://github.com/cp3-llbb/cp3-llbb.github.io/blob/source/mkdocs.yml#L14) and [this](https://github.com/cp3-llbb/cp3-llbb.github.io/blob/source/mkdocs.yml#L28-L35) - the site is [here](http://cp3-llbb.github.io), doxygen link under Framework > Doxygen on the left).
